image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'npm install'
    command: npm run serve

vscode:
  extensions:
    - octref.vetur@0.27.0:a+OljFHzmH1YrzbM13sMhQ==

ports:
  - port: 8080
    onOpen: open-browser

  - port: 8000
    onOpen: open-browser